---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-server
  labels:
    app: greeter-service
spec:
  selector:
    matchLabels:
      app: greeter-service
  replicas: 2
  template:
    metadata:
      labels:
        app: greeter-service
    spec:
      containers:
      - name: add
        image: service/greeter
        imagePullPolicy: IfNotPresent
        ports:
        - name: grpc
          protocol: TCP
          containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: greeter-service
spec:
  selector:
    app: greeter-service
  ports:
    - name: grpc
      port: 3000
      targetPort: 3000
      protocol: TCP
